-- =========================================================================
-- V1__init_schema.sql: Initial Database Schema for Money Transfer Service
-- =========================================================================

-- 1. Accounts Table
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(32) NOT NULL UNIQUE,
    account_holder_name VARCHAR(128) NOT NULL,
    balance NUMERIC(19, 4) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'NGN',
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_account_number ON accounts(account_number);

-- 2. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference VARCHAR(64) NOT NULL UNIQUE,
    source_account_number VARCHAR(32) NOT NULL,
    destination_account_number VARCHAR(32) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    transaction_fee NUMERIC(19, 4) NOT NULL,
    billed_amount NUMERIC(19, 4) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    status_message VARCHAR(255),
    commission_worthy BOOLEAN,
    commission NUMERIC(19, 4),
    commission_processed_at TIMESTAMP,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tx_reference ON transactions(transaction_reference);
CREATE INDEX IF NOT EXISTS idx_tx_source_acc ON transactions(source_account_number);
CREATE INDEX IF NOT EXISTS idx_tx_dest_acc ON transactions(destination_account_number);
CREATE INDEX IF NOT EXISTS idx_tx_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_tx_created_at ON transactions(date_created);
CREATE INDEX IF NOT EXISTS idx_tx_commission_eval ON transactions(status, commission_worthy);

-- 3. Daily Transaction Summaries Table
CREATE TABLE IF NOT EXISTS daily_transaction_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary_date DATE NOT NULL UNIQUE,
    total_transactions BIGINT NOT NULL,
    successful_transactions BIGINT NOT NULL,
    failed_transactions BIGINT NOT NULL,
    insufficient_funds_transactions BIGINT NOT NULL,
    total_volume NUMERIC(19, 4) NOT NULL,
    total_fees NUMERIC(19, 4) NOT NULL,
    total_commission NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_summary_date ON daily_transaction_summaries(summary_date);

-- 4. ShedLock Table for Multi-Pod Kubernetes Distributed Lock Coordination
CREATE TABLE IF NOT EXISTS shedlock (
    name VARCHAR(64) NOT NULL PRIMARY KEY,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL
);
