-- =========================================================================
-- V3__security_users_and_otp.sql: Security Users and OTP Transfer Sessions
-- =========================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'ROLE_USER',
    account_number VARCHAR(32) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_account FOREIGN KEY (account_number) REFERENCES accounts(account_number)
);

CREATE INDEX IF NOT EXISTS idx_user_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_user_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_user_account ON users(account_number);

-- 2. Transfer OTP Sessions Table (for 2FA Transfer Authorization)
CREATE TABLE IF NOT EXISTS transfer_otp_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL UNIQUE,
    username VARCHAR(64) NOT NULL,
    source_account_number VARCHAR(32) NOT NULL,
    destination_account_number VARCHAR(32) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    transaction_fee NUMERIC(19, 4) NOT NULL,
    billed_amount NUMERIC(19, 4) NOT NULL,
    description VARCHAR(255),
    transaction_reference VARCHAR(64),
    otp_code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_otp_session_id ON transfer_otp_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_otp_username ON transfer_otp_sessions(username);
CREATE INDEX IF NOT EXISTS idx_otp_status ON transfer_otp_sessions(status);

-- 3. Seed Users (Password: "Password123!")
-- BCrypt hash for "Password123!": $2a$10$R1MntVvVg9yyxPopnLosCeFSy2OWb2F4q2gMDAEe7E1NxAtfETdZu
INSERT INTO users (username, email, password_hash, role, account_number, created_at, updated_at)
VALUES
    ('emmanuel', 'emmanuel@dotlabs.ai', '$2a$10$R1MntVvVg9yyxPopnLosCeFSy2OWb2F4q2gMDAEe7E1NxAtfETdZu', 'ROLE_USER', '1000000001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ekene', 'ekene@dotlabs.ai', '$2a$10$R1MntVvVg9yyxPopnLosCeFSy2OWb2F4q2gMDAEe7E1NxAtfETdZu', 'ROLE_USER', '1000000002', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('ikemefuna', 'ikemefuna@dotlabs.ai', '$2a$10$R1MntVvVg9yyxPopnLosCeFSy2OWb2F4q2gMDAEe7E1NxAtfETdZu', 'ROLE_USER', '1000000003', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('admin', 'admin@dotlabs.ai', '$2a$10$R1MntVvVg9yyxPopnLosCeFSy2OWb2F4q2gMDAEe7E1NxAtfETdZu', 'ROLE_ADMIN', '1000000004', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
